### ISSUE TITLE
Index and Range do not work on NetFx and NetStd2.0

### ISSUE THREAD

**Issue by mattjohnsonpint** [SimonCropp/Polyfill#12]
The [Index and Range polyfills](https://github.com/SimonCropp/Polyfill#index-and-range) don't work on .NET Framework and .NET Standard 2.0 targets.

Steps to reproduce:
- Create a class library targeting either `netstandard2.0` or any .NET Framework version, such as `net48`
- Add code that uses index or ranges
- Set language level latest, and add Polyfill nuget package
- Compile

The build fails with:

```
[CS0656] Missing compiler required member 'System.Runtime.CompilerServices.RuntimeHelpers.GetSubArray'
```

**Comment by SimonCropp** [comment]
i cant repro this. can u share a full repro?

**Comment by mattjohnsonpint** [comment]
Also, string range works on Polyfill 1.7.0 with .NET Framework (any version) even without reference to System.ValueTuple.

**Comment by Metadorius** [comment]
@SimonCropp for some reason it still doesn't work for me. .NET Framework 4.8, added ValueTuple reference and Polyfill reference, complains about predefined type `System.Range` (same with index) not being found.

**Comment by SimonCropp** [comment]
@Metadorius happy to accept a PR that fixes this

**Comment by SadPencil** [comment]
> @Metadorius happy to accept a PR that fixes this

I am working on the same project as @Metadorius does. 

The latest finding is that if I compile Polyfill with the following two lines commented out in `src/Polyfill/IndexRange/Index.cs` and `src/Polyfill/IndexRange/Range.cs` files: 
```cs
#if (NET46X && VALUETUPLEREFERENCED) || NET47X || NET48X || NETSTANDARD2_0 || NETCOREAPP2X` 
#endif
```
then this issue disappears. However I have not figured out why.

**Comment by SadPencil** [comment]
@SimonCropp Here is a minimal repo to reproduce this issue: https://github.com/SadPencil/polyfill-index-range-issue

This is a `net48` project with the new .csproj format. All three dependencies have been explicitly imported: `System.Memory`, `System.Threading.Tasks.Extensions`, and `System.ValueTuple`. However, as long as the source code contains index/range syntax `var substring = "value"[2..];` the build fails with `error CS0518: Predefined type 'System.Range' is not defined or imported`.

The repo I have provided should be sufficient to reproduce this issue. Personally, I suspect that constant `NET48X` might not be correctly defined as in `Polyfill.props` does, however I have no idea about why and thus can not make a PR for a fix.

```xml
  <PropertyGroup>
    <LowerFramework>$(TargetFramework.ToLower())</LowerFramework>
  </PropertyGroup>
  <PropertyGroup Condition="$(LowerFramework.StartsWith('net48'))">
    <DefineConstants>$(DefineConstants);NET48X</DefineConstants>
  </PropertyGroup>
```
